using McpServer.Models;
using System.Text.Json;

namespace McpServer.Infrastructure.Salesforce;

/// <summary>
/// Loads Salesforce object schemas from JSON files in the schema directory.
/// Schemas are generated by the download script and must not be hardcoded.
/// </summary>
public class SchemaRegistry
{
    private readonly string _schemaDirectory;
    private readonly ILogger<SchemaRegistry> _logger;
    private readonly Dictionary<string, SalesforceObjectSchema> _schemas = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, string> _labelToApiName = new(StringComparer.OrdinalIgnoreCase);

    public SchemaRegistry(IConfiguration config, ILogger<SchemaRegistry> logger)
    {
        _schemaDirectory = config["Schema:SchemaDirectory"] ?? "./schemas";
        _logger = logger;
        LoadSchemas();
    }

    private void LoadSchemas()
    {
        if (!Directory.Exists(_schemaDirectory))
        {
            _logger.LogWarning("Schema directory '{Dir}' not found. No schemas loaded.", _schemaDirectory);
            return;
        }

        foreach (var file in Directory.GetFiles(_schemaDirectory, "*.json"))
        {
            try
            {
                var json = File.ReadAllText(file);
                var schema = JsonSerializer.Deserialize<SalesforceObjectSchema>(json,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (schema != null && !string.IsNullOrEmpty(schema.Name))
                {
                    _schemas[schema.Name] = schema;
                    _labelToApiName[schema.Label] = schema.Name;
                    _labelToApiName[schema.LabelPlural] = schema.Name;
                    _logger.LogInformation("Loaded schema: {Object} ({Fields} fields)", schema.Name, schema.Fields.Count);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to load schema from {File}", file);
            }
        }

        _logger.LogInformation("Total schemas loaded: {Count}", _schemas.Count);
    }

    public SalesforceObjectSchema? GetSchema(string nameOrLabel)
    {
        if (_schemas.TryGetValue(nameOrLabel, out var schema))
            return schema;

        if (_labelToApiName.TryGetValue(nameOrLabel, out var apiName))
            return _schemas.GetValueOrDefault(apiName);

        return null;
    }

    public string? ResolveObjectName(string nameOrLabel)
    {
        if (_schemas.ContainsKey(nameOrLabel))
            return nameOrLabel;

        if (_labelToApiName.TryGetValue(nameOrLabel, out var apiName))
            return apiName;

        // Fuzzy match: find schema where name starts with input
        var lower = nameOrLabel.ToLowerInvariant();
        var match = _schemas.Keys.FirstOrDefault(k => k.ToLowerInvariant().StartsWith(lower))
                    ?? _labelToApiName.Keys.FirstOrDefault(k => k.ToLowerInvariant().StartsWith(lower));

        if (match != null && _labelToApiName.TryGetValue(match, out var resolved))
            return resolved;

        return _schemas.Keys.FirstOrDefault(k => k.ToLowerInvariant().Contains(lower));
    }

    public IEnumerable<SalesforceObjectSchema> GetAllSchemas() => _schemas.Values;

    public string? ResolveFieldName(SalesforceObjectSchema schema, string nameOrLabel)
    {
        var exact = schema.Fields.FirstOrDefault(f =>
            f.Name.Equals(nameOrLabel, StringComparison.OrdinalIgnoreCase) ||
            f.Label.Equals(nameOrLabel, StringComparison.OrdinalIgnoreCase));

        if (exact != null) return exact.Name;

        var lower = nameOrLabel.ToLowerInvariant();
        return schema.Fields
            .FirstOrDefault(f => f.Name.ToLowerInvariant().Contains(lower) ||
                                 f.Label.ToLowerInvariant().Contains(lower))
            ?.Name;
    }

    public List<string> GetDefaultFields(SalesforceObjectSchema schema)
    {
        // Returns common fields + Id, Name/subject equivalents
        var defaults = new List<string> { "Id" };
        var priority = new[] { "Name", "Subject", "Title", "Email", "Phone", "Status", "Type",
                                "CreatedDate", "LastModifiedDate", "OwnerId" };

        foreach (var p in priority)
        {
            if (schema.Fields.Any(f => f.Name.Equals(p, StringComparison.OrdinalIgnoreCase)))
                defaults.Add(p);
        }

        return defaults.Distinct().Take(10).ToList();
    }

    public void Reload()
    {
        _schemas.Clear();
        _labelToApiName.Clear();
        LoadSchemas();
    }
}
